### ISSUE TITLE
SyntaxError: Use of const in strict mode. in /node_modules/quasar-cli/node_modules/ora/index.js:2

### ISSUE THREAD

**Issue by vedmant** [rstoenescu/quasar-framework#111]
Hi,
I have following issue with using `quasar init`:

/usr/local/lib/node_modules/quasar-cli/node_modules/ora/index.js:2
const chalk = require('chalk');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/quasar-cli/bin/quasar-init:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I use Mac OS El Captain, I tried to delete node and npm completely and reinstall it with `brew install node`, then I installed Quasar cli `npm install -g quasar-cli`, but still getting the same error. 
My installed node version: v0.12.14
NPM version: 3.8.6

Thanks!

**Comment by rstoenescu** [comment]
Thanks for logging this.

Node v0.12 is very outdated. Try installing node v4, the LTS version.

**Comment by vedmant** [comment]
Thanks! It appeared that I had node v0.12 installed alongside of brew installation. Sorry for not relevant issue.

**Comment by rstoenescu** [comment]
Don't worry. I'm glad it's all good now!
