### ISSUE TITLE
Getting started miss 'npm install'

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#16]
When following the new 0.5.0 "Getting started", after 'quasar init', 'quasar dev' command throws the following error :

```
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (J:\disque\workspace\sarqua\build\script.dev.js:3:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

It's because node modules are not installed yet. We have to add a 'npm install' step just after the 'quasar init' step.

**Comment by rstoenescu** [comment]
You're right. Added 'npm install' step.
