### ISSUE TITLE
Win10x64 Error to wrap cordova

### ISSUE THREAD

**Issue by eullercristian** [rstoenescu/quasar-framework#68]
@rstoenescu I have a error when a type quasar wrap cordova, follow error bellow:

`quasar wrap cordova

? Install Crosswalk WebView plugin for Android Apps (HIGHLY recommended) Yes

Creating a new cordova project.
fs.js:1054
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink '..\dist' -> 'E:\WEBPESSOAL\telelista\cordova\www'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at Object.symlink (C:\Users\euller\AppData\Roaming\npm\node_modules\quasar-cli\lib\qfs.js:54:13)
    at ChildProcess.spawn.callback (C:\Users\euller\AppData\Roaming\npm\node_modules\quasar-cli\bin\quasar-wrap:84:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)`

Can you help me?

Thanks

**Comment by rstoenescu** [comment]
Hi, this is documented.
http://quasar-framework.org/guide/cordova-wrapper.html#Wrap-your-App

Check the note for Windows developers.
